In [1]:
%load_ext autoreload
%autoreload 2

import os
import sys
import yaml
import json
import numpy as np
import pandas as pd
from pytorch_lightning import Trainer
from Bio import SeqIO

sys.path.append(os.path.join(os.path.dirname(os.getcwd()), 'src'))

from frustraiseq.data.dataloader import FunstrationDataModule
from frustraiseq.model.frustraiseq import FrustrAISeq

/Users/janleusch/anaconda3/envs/biotrainer/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# general info for script

## 1) Load Data
First we load a simple fasta file containing the headers/ids and their sequences and store it in a pd.DataFrame. Make sure to name the cols id and sequence

In [2]:
fasta_file_path = "../data/example_seqs.fasta"

In [3]:
sequences = []
ids = []
with open(fasta_file_path, 'r') as handle:
    for record in SeqIO.parse(handle, "fasta"):
        ids.append(record.id)
        sequences.append(str(record.seq))

In [13]:
sequences[2] = "SEQV" * 128 + "ENCES"
print(len(sequences[2]))

517

In [14]:
df = pd.DataFrame({
    'id': ids,
    'sequence': sequences
})
df

     id                                           sequence
0  Seq1                                           SEQVENCE
1  Seq2                                           SEQVINCE
2  Seq3  SEQVSEQVSEQVSEQVSEQVSEQVSEQVSEQVSEQVSEQVSEQVSE...

## 2) Load Model
Now lets load the config, pLM model, model checkpoint. If protT5 and FurstrAI-Seq are not already locally available download them and specify their location in the config

In [15]:
# load config.yaml corresponding to the model to be used.
with open(f"../src/frustraiseq/config/default_config.yml", 'r') as f:
    config = yaml.safe_load(f)
config["experiment_name"]

'FrustrAI-Seq_Prediction'

In [ ]:
# Load pLM model and tokenizer, save them locally and update config with local path
"""
from transformers import T5EncoderModel, T5Tokenizer
encoder = T5EncoderModel.from_pretrained("Rostlab/prot_t5_xl_half_uniref50-enc")
tokenizer = T5Tokenizer.from_pretrained("Rostlab/prot_t5_xl_half_uniref50-enc")

encoder.save_pretrained("./prot_t5_xl_half_uniref50-enc")
tokenizer.save_pretrained("./prot_t5_xl_half_uniref50-enc")
del encoder
del tokenizer
config["pLM_model"] = "./prot_t5_xl_half_uniref50-enc"
"""

In [ ]:
# Load model checkpoint, save it locally and update config with local path
"""
from huggingface_hub import hf_hub_download
   
local_path = hf_hub_download(
    repo_id="leuschj/FrustrAI-Seq",
    filename="FrustraSeq_CW.ckpt",
    local_dir="./FrustrAI-Seq",
)
config["checkpoint_path"] = local_path
"""

In [18]:
# or set paths directly in the config if already downloaded
config["pLM_model"] = "../prot_t5_xl_half_uniref50-enc"
config["checkpoint_path"] = "../FrustrAI-Seq/FrustraSeq_CW.ckpt"

In [19]:
config["batch_size"] = 2 # adjust this based on your GPU memory

In [20]:
model = FrustrAISeq.load_from_checkpoint(checkpoint_path=config["checkpoint_path"],
                                         config=config)

RANK -1: Loaded pLM model ../prot_t5_xl_half_uniref50-enc
RANK -1: Using LoRA fine-tuning for ['q', 'k', 'v', 'o'] layers
trainable params: 1,967,104 || all params: 1,210,107,904 || trainable%: 0.1626
RANK -1: Using half precision.
RANK -1: Applying class weights for CrossEntropyLoss: [2.65750085, 0.68876299, 0.8533673]
RANK -1: Loaded surprisal dictionary.
RANK -1: Model initialized.

In [21]:
predict_data_module = FunstrationDataModule(
                                            config=config,
                                            inference_dataset=df,
                                            batch_size=config["batch_size"],
                                            num_workers=config["num_workers"],
                                            persistent_workers=False, 
                                            pin_memory=True
                                        )

## 3) Inference

Lets define a Lightning trainer and run inference (prediction)

In [22]:
#adjust dataloader parameters as needed. 
trainer = Trainer(
    accelerator="auto",
    logger=False,
)

💡 Tip: For seamless cloud uploads and versioning, try installing [litmodels](https://pypi.org/project/litmodels/) to enable LitModelCheckpoint, which syncs automatically with the Lightning model registry.
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
HPU available: False, using: 0 HPUs

In [23]:
predictions = trainer.predict(model, predict_data_module)

Created test dataset for prediction
Test dataset size: 3 samples

/Users/janleusch/anaconda3/envs/biotrainer/lib/python3.12/site-packages/pytorch_lightning/trainer/connectors/data_connector.py:428: Consider setting `persistent_workers=True` in 'predict_dataloader' to speed up the dataloader worker initialization.
/Users/janleusch/anaconda3/envs/biotrainer/lib/python3.12/site-packages/torch/utils/data/dataloader.py:683: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, then device pinned memory won't be used.
  warnings.warn(warn_msg)

Predicting: |          | 0/? [00:00<?, ?it/s]
During prediction sequence length limit will always be the longest sequence in the batch, so consider using batch size of 1 for inference to minimize memory usage.

Predicting DataLoader 0: 100%|██████████| 2/2 [00:03<00:00,  0.55it/s]

In [24]:
results = []
for pred_batch in predictions:
    if pred_batch is not None:
        results.extend(pred_batch)

df_output = pd.DataFrame(results)
df_output

       id residue  frustration_index  frustration_class   entropy  surprisal
0    Seq1       S           0.227972                  1  0.825555   1.305152
1    Seq1       E          -0.246422                  0  0.844296   0.492788
2    Seq1       Q          -0.034213                  1  0.851429   1.333002
3    Seq1       V           0.576841                  2  0.771738  -1.859438
4    Seq1       E          -0.319172                  0  0.842315   0.404803
..    ...     ...                ...                ...       ...        ...
528  Seq3       E          -0.612065                  0  0.715259   0.050574
529  Seq3       N          -0.538467                  0  0.718024  -0.016696
530  Seq3       C           0.836955                  2  0.625885  -1.052248
531  Seq3       E          -0.477138                  0  0.744590   0.213756
532  Seq3       S          -0.005205                  1  0.662342   0.805150

[533 rows x 6 columns]

Use entropy and surprisal score to filter trough predictions. Below is an example where want to filter for residues in which the model is confident (entropy >= 0.5) but its unlikely to observe this value given the amino acids frustration distribution (-1 >= surprisal score OR surprisal score > 1). A surprisal score of 1 means that the predicted regression value is one standart deviations away from its AA mean. Feel free to play around with both scores :)

In [25]:
df_output.loc[(df_output["entropy"] < 0.5) & ((df_output["surprisal"] > 1) | (df_output["surprisal"] < -1))]

       id residue  frustration_index  frustration_class   entropy  surprisal
12   Seq2       I           0.767246                  2  0.481139  -1.602786
19   Seq3       V           0.712662                  2  0.451144  -1.455910
39   Seq3       V           0.659800                  2  0.486167  -1.612965
43   Seq3       V           0.677995                  2  0.449020  -1.558905
47   Seq3       V           0.677606                  2  0.456517  -1.560062
..    ...     ...                ...                ...       ...        ...
467  Seq3       V           0.834915                  2  0.288811  -1.092695
471  Seq3       V           0.846131                  2  0.318471  -1.059371
495  Seq3       V           0.852288                  2  0.249091  -1.041078
499  Seq3       V           0.836904                  2  0.312368  -1.086784
503  Seq3       V           0.855354                  2  0.374313  -1.031970

[108 rows x 6 columns]

In [ ]:
df_output.to_csv("predictions.csv", index=False)